### ISSUE TITLE
Connection path update for non-connected connection

### ISSUE THREAD

**Issue by yspreen** [retejs/connection-plugin#23]
I think it's easiest if you just look at this gif:

![gif](https://i.imgur.com/mPWCNtH.gif)

I call

    editor.view.updateConnections({ node });
on every (dis)connect, after a short delay.  
This works to update connections after they were made, but dangling connections aren't properly updated.

What can I do to prevent this?

**Comment by Ni55aN** [comment]
I figures out what is a problem. You can force update the pseudo connection as follows:

```js
editor.trigger('mousemove', { ...editor.view.area.mouse });
```

Rete.js itself doesn't listen sockets positions due to performance reasons, therefore you need to update it manually

> I also noticed that the connection completely disappears only if the second node has a type selected which changes the height? 

`mouseup` event has triggered, which leads to the performing of the add/drop action. I'll try find a workaround for this case

**Comment by vamidi** [comment]
Hi, I am probably trying the same thing, how can you re-render the node in order to get the connections right?

example - https://gyazo.com/ae515e0942c35e662e461a86f8c311fd

I tried using this snippet.

```js
this.editor.trigger('mousemove', { ...this.editor.view.area.mouse });
this.editor.view.updateConnections({ node: this.node });
this.node.update();
```

[EDIT] When I add a timeout it works, but I don't want it to we a 'race' condition, so when can I trigger the changes?
```js
setTimeout(() => {
	this.editor.trigger('mousemove', { ...this.editor.view.area.mouse });
	this.editor.view.updateConnections({ node: this.node });
	this.node.update();
}, 50);
```
