### ISSUE TITLE
Picking a connections triggers connectiondrop on the editor

### ISSUE THREAD

**Issue by nikola-bozin-org** [retejs/connection-plugin#57]
![code](https://github.com/retejs/connection-plugin/assets/112718743/ac1de499-4ba9-4f85-91df-969aca543248)
![editor](https://github.com/retejs/connection-plugin/assets/112718743/b6e863a1-2919-4e2c-a56a-245a403ec997)

As you can see in the images. I picked a connection and it triggered the drop event.

**Also, can you access the picked connection HTML element? It's essential for me so I can style it.**

**Comment by Ni55aN** [comment]
v1 does not support customizing the picked connection separately. The only way is to style all connections with the `.connection .main-path` selector
Regarding `connectiondrop`, this is really not the expected behavior (because connection drop has two strategies). I will add this issue to the backlog, but it will probably not be resolved soon since the priority is tasks for v2

**Comment by nikola-bozin-org** [comment]
Well.. thanks for you answer. I guess il have to do some DOM manipulations than.

**Comment by Ni55aN** [comment]
or you can migrate the project to the v2 beta (if this is relevant for you), since it is much more flexible. Certainly, there is a possibility of breaking changes, but it is unlikely that they will have a substantial impact.

**Comment by nikola-bozin-org** [comment]
Yeah.. there is plan to migrate... but currently not in a hurry.. i checked the docs of v2 but there is nothing specific that can help me with implentations.
Thanks anyway!
